### ISSUE TITLE
The bot goes offline after a while

### ISSUE THREAD

**Issue by siddop7** [navaneethkm004/discord-24x7-music#1]
The bot goes offline after a while. If i turn off the repl.it then it goes offline after 5 or 10 mins. I want it to be online forever. Pls fix this issue.

**Comment by navaneethkm004** [comment]
Yea, so you should probably get a link with `.repl.co` extension in the bot's repl. So copy that link and paste it in https://pingle.repl.co after making an account. It will keep your bot online
